version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

  queue:
    image: schickling/beanstalkd:latest

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    depends_on:
      - queue
