version: '3'

services:
  nginx:
    image: nginx:1.15.2-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:7.1.20-fpm-alpine
    volumes:
      - ./:/app

  queue:
    image: schickling/beanstalkd:latest

  worker:
    image: php:7.1.20-cli-alpine
    volumes:
      - ./:/app
    command: php /app/code/worker.php
    depends_on:
      - queue
