version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
